<?php

namespace AppBundle\Repository;

/**
 * AppFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppFormRepository extends \Doctrine\ORM\EntityRepository
{
}
