# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        pdo_mysql:
            entity:
                class: AppBundle:User
                property: email
        in_memory:
            memory: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: pdo_mysql
            form_login:
                login_path: login
                check_path: login

                # field names for the username and password fields
                username_parameter: _email
                password_parameter: _password

                # Default redirection
                default_target_path: /appform
            logout:
                path:   /logout
                target: /

            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
